version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
  db:
    container_name: mysql
    build:
      context: .
      dockerfile: Dockerfile_mysql
    #command:
    #  - default-authentication-plugin = mysql_native_password

    command: --default-authentication-plugin=mysql_native_password

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      #PMA_USER: root
      #PMA_PASSWORD: root
    ports:
      - "3307:3306"
    #volumes:
    #  - db-vol:/var/www/html/mysql

#volumes:
#  db-vol: